package com.heb.enterprise.coms.service;



import com.heb.enterprise.coms.service.CodeTablesService.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import com.heb.enterprise.coms.dao.CodeTablesDAO;
import com.heb.enterprise.coms.model.vo.DynamicDataVO;
import com.heb.enterprise.coms.model.vo.MetaDataVO;
import com.heb.enterprise.coms.utils.COMSException;
import com.heb.enterprise.coms.utils.CodeTablesParser;
import com.heb.enterprise.coms.utils.Constants;
public class CodeTablesServiceTest {

	@Test 
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(CodeTablesService.class, notNullValue());
	}

	@Test 
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		CodeTablesService target = new CodeTablesService();
		assertThat(target, notNullValue());
	}

}
